// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadResults():Promise<string>;

export function LoadSettings():Promise<string>;

export function SaveResults(arg1:string):Promise<boolean>;

export function SaveSettings(arg1:string):Promise<boolean>;
