// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchScores() {
  return window['go']['main']['App']['FetchScores']();
}

export function LoadResults() {
  return window['go']['main']['App']['LoadResults']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveResults(arg1) {
  return window['go']['main']['App']['SaveResults'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
